model = "gpt-5.1-codex-max"
model_reasoning_effort = "xhigh"
[projects."/Users/eyad/Public/Projects"]
trust_level = "trusted"

[projects."/Users/eyad/Public/Projects/IBG/ios"]
trust_level = "trusted"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true

[mcp_servers.XcodeBuildMCP]
command = "npx"
args = ["-y", "xcodebuildmcp@latest"]
env = { "INCREMENTAL_BUILDS_ENABLED" = "false", "XCODEBUILDMCP_SENTRY_DISABLED" = "false" }